name: deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  generatesite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - name: Generate site
        run: make web
        env:
          BASE_URL: '/releases'
      - name: Deploy site
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: _site
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
